name: Deploy to Windows Dev

on:
  pull_request:
    types: [closed]
    branches:
      - dev

jobs:
  windows-deploy:
    runs-on: ubuntu-latest
    env:
      DB_HOST: ${{ secrets.DEV_DB_HOST }}
      DB_PW: ${{ secrets.DEV_DB_PW}}
      DB_USER: ${{ secrets.DEV_DB_USER }}
      DB_NAME: ${{ secrets.DEV_DB_NAME }}
      VUE_APP_CLIENT_ID: ${{secrets.VUE_APP_CLIENT_ID}}
      VITE_APP_CLIENT_ID: ${{secrets.VITE_APP_CLIENT_ID}}
      VITE_APP_API_URL: ${{secrets.VITE_APP_API_URL}}
      VITE_APP_CLIENT_URL: ${{secrets.VITE_APP_CLIENT_URL}}
      GOOGLE_AUDIENCE: ${{secrets.GOOGLE_AUDIENCE}}
      CLIENT_SECRET: ${{secrets.CLIENT_SECRET}}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: dev
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install
      - run: npm run build

      - name: Copy folder content recursively to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: dist/
          remote: c:/Apache24/htdocs/peformance
          recursive: true
          host: "performancedev.oc.edu"
          username: "david.north"
          privateKey: ${{ secrets.DEV_WIN_SERVER_SSH_KEY  }}
